language: go

os:
  - linux

go:
  - "1.10"

install:
  - make dependencies
  - glyphcheck ./...
  - make dev

script: make test && make test-long && make cover && make bench

sudo: false

notifications:
  email: false
